name       : laszip
version    : 3.4.3
release    : 1
source     :
    - https://github.com/LASzip/LASzip/releases/download/3.4.3/laszip-src-3.4.3.tar.bz2 : 5775eb0b97de1b77514d47534cc65c6cfb5bebdd8aed0e47a23af8e75b7ea887
hompage    : https://laszip.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : LASzip brings free and lossless LiDAR compression
description: |
    LASzip quickly turns bulky LAS files into compact LAZ files without information loss.
setup      : |
    %patch -p1 < $pkgfiles/generate-pkg-config.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
